#!/usr/bin/env python3
"""Translate guide pages from English to Chinese."""
import os, re

BASE = 'docs/zh/connect-iq'
ENBASE = 'docs/en/connect-iq'

# English -> Chinese replacements for guide pages
REPLACEMENTS = [
    # app-review-guidelines
    ('App Review Guidelines', '应用审核指南'),
    ('This document describes the guidelines for submitting apps to the Connect IQ Store.', '本文档描述提交应用到 Connect IQ 商店的审核指南。'),
    ('App Submission Requirements', '应用提交要求'),
    ('All apps must comply with these guidelines to be accepted.', '所有应用必须遵守这些指南才能被接受。'),
    ('Content Guidelines', '内容指南'),
    ('Apps must not contain offensive or inappropriate content.', '应用不得包含冒犯性或不适当的内容。'),
    ('Technical Requirements', '技术要求'),
    ('Apps must not crash or cause instability on the device.', '应用不得导致设备崩溃或不稳定。'),
    ('Performance Guidelines', '性能指南'),
    ('Apps must not drain the battery excessively.', '应用不得过度消耗电量。'),
    ('Apps must complete startup within a reasonable time.', '应用必须在合理时间内完成启动。'),
    ('UI Guidelines', '用户界面指南'),
    ('Apps must follow the Garmin UI conventions.', '应用必须遵循 Garmin 用户界面规范。'),
    ('App Submission Process', '应用提交流程'),
    ('Submit your app through the Connect IQ SDK Manager.', '通过 Connect IQ SDK Manager 提交应用。'),
    ('Review Process', '审核流程'),
    ('Apps are reviewed for compliance with these guidelines.', '应用将按这些指南进行审核。'),
    ('Common Rejection Reasons', '常见拒绝原因'),
    ('Apps that do not follow the guidelines will be rejected.', '不遵守指南的应用将被拒绝。'),
    ('Please ensure your app meets all requirements before submitting.', '提交前请确保应用满足所有要求。'),
    ('For more information, see the Connect IQ documentation.', '更多信息请参阅 Connect IQ 文档。'),
    ('App Update Guidelines', '应用更新指南'),
    ('Updates must also comply with these guidelines.', '更新也必须遵守这些指南。'),
    ('App Removal', '应用移除'),
    ('Apps that violate guidelines may be removed from the store.', '违反指南的应用可能会从商店移除。'),
    ('Developer Account', '开发者账户'),
    ('You must have a developer account to submit apps.', '您必须拥有开发者账户才能提交应用。'),
    ('App Listing Requirements', '应用列表要求'),
    ('Apps must have a proper icon, name, and description.', '应用必须有适当的图标、名称和描述。'),
    ('Screenshots', '截图'),
    ('Provide screenshots showing your app in use.', '提供展示应用使用情况的截图。'),
    ('Privacy Policy', '隐私政策'),
    ('Apps that collect user data must include a privacy policy.', '收集用户数据的应用必须包含隐私政策。'),
    ('Terms of Service', '服务条款'),
    ('Apps must comply with Garmin\'s terms of service.', '应用必须遵守 Garmin 的服务条款。'),
    ('Intellectual Property', '知识产权'),
    ('Apps must not infringe on third-party intellectual property.', '应用不得侵犯第三方知识产权。'),
    ('Prohibited Content', '禁止内容'),
    ('Apps must not contain illegal or harmful content.', '应用不得包含非法或有害内容。'),
    ('App Quality', '应用质量'),
    ('Apps must be fully functional and tested.', '应用必须功能完整并经过测试。'),
    ('Compatibility', '兼容性'),
    ('Apps must work on all supported devices.', '应用必须在所有支持的设备上运行。'),
    ('Security', '安全'),
    ('Apps must not compromise device security.', '应用不得损害设备安全。'),
    ('Data Privacy', '数据隐私'),
    ('Apps must protect user data privacy.', '应用必须保护用户数据隐私。'),
    ('Advertising', '广告'),
    ('Apps must comply with advertising guidelines.', '应用必须遵守广告指南。'),
    ('In-App Purchases', '应用内购买'),
    ('In-app purchases must follow store policies.', '应用内购买必须遵循商店政策。'),
    ('App Categories', '应用分类'),
    ('Select the appropriate category for your app.', '为您的应用选择适当的分类。'),
    ('App Versioning', '应用版本管理'),
    ('Version numbers must follow semantic versioning.', '版本号必须遵循语义化版本管理。'),
    ('Changelog', '更新日志'),
    ('Provide a changelog for each release.', '为每个版本提供更新日志。'),
    ('Support', '支持'),
    ('Provide support contact information.', '提供支持联系方式。'),
    ('Testing', '测试'),
    ('Test your app thoroughly before submitting.', '提交前彻底测试您的应用。'),
    ('Documentation', '文档'),
    ('Include documentation for your app.', '为您的应用包含文档。'),
    ('Localization', '本地化'),
    ('Provide localized content where applicable.', '在适用的情况下提供本地化内容。'),
    ('Accessibility', '无障碍'),
    ('Apps must be accessible to all users.', '应用必须对所有用户无障碍。'),
    ('App Lifecycle', '应用生命周期'),
    ('Apps must handle lifecycle events properly.', '应用必须正确处理生命周期事件。'),
    ('Background Operations', '后台操作'),
    ('Background operations must be efficient.', '后台操作必须高效。'),
    ('Memory Management', '内存管理'),
    ('Apps must manage memory efficiently.', '应用必须高效管理内存。'),
    ('Battery Usage', '电池使用'),
    ('Apps must minimize battery usage.', '应用必须最小化电池使用。'),
    ('Network Usage', '网络使用'),
    ('Apps must minimize network usage.', '应用必须最小化网络使用。'),
    ('Data Usage', '数据使用'),
    ('Apps must minimize data usage.', '应用必须最小化数据使用。'),
    ('Storage Usage', '存储使用'),
    ('Apps must minimize storage usage.', '应用必须最小化存储使用。'),
    ('API Usage', 'API 使用'),
    ('Apps must use APIs correctly.', '应用必须正确使用 API。'),
    ('API Limitations', 'API 限制'),
    ('Apps must respect API limitations.', '应用必须遵守 API 限制。'),
    ('API Deprecation', 'API 弃用'),
    ('Apps must handle deprecated APIs gracefully.', '应用必须优雅地处理已弃用的 API。'),
    ('API Changes', 'API 变更'),
    ('Apps must handle API changes.', '应用必须处理 API 变更。'),
    ('API Compatibility', 'API 兼容性'),
    ('Apps must maintain API compatibility.', '应用必须保持 API 兼容性。'),
    ('API Documentation', 'API 文档'),
    ('Document your API usage.', '记录您的 API 使用情况。'),
    ('Code Quality', '代码质量'),
    ('Code must be clean and maintainable.', '代码必须干净且可维护。'),
    ('Code Style', '代码风格'),
    ('Follow the recommended code style.', '遵循推荐的代码风格。'),
    ('Code Review', '代码审查'),
    ('Review your code before submitting.', '提交前审查您的代码。'),
    ('Code Optimization', '代码优化'),
    ('Optimize your code for performance.', '优化代码以提升性能。'),
    ('Code Security', '代码安全'),
    ('Secure your code against vulnerabilities.', '保护代码免受漏洞侵害。'),
    ('Code Testing', '代码测试'),
    ('Test your code thoroughly.', '彻底测试您的代码。'),
    ('Code Coverage', '代码覆盖率'),
    ('Achieve high code coverage.', '实现高代码覆盖率。'),
    ('Code Standards', '代码标准'),
    ('Follow the coding standards.', '遵循编码标准。'),
    ('Code Conventions', '代码约定'),
    ('Follow the coding conventions.', '遵循编码约定。'),
    ('Code Best Practices', '代码最佳实践'),
    ('Follow best practices for coding.', '遵循编码最佳实践。'),
    ('Code Patterns', '代码模式'),
    ('Use appropriate code patterns.', '使用适当的代码模式。'),
    ('Code Structure', '代码结构'),
    ('Organize your code properly.', '正确组织您的代码。'),
    ('Code Organization', '代码组织'),
    ('Organize your code for maintainability.', '为可维护性组织您的代码。'),
    ('Code Modularity', '代码模块化'),
    ('Use modular code design.', '使用模块化代码设计。'),
    ('Code Reusability', '代码可重用性'),
    ('Write reusable code.', '编写可重用的代码。'),
    ('Code Readability', '代码可读性'),
    ('Write readable code.', '编写可读的代码。'),
    ('Code Simplicity', '代码简洁性'),
    ('Keep code simple.', '保持代码简洁。'),
    ('Code Efficiency', '代码效率'),
    ('Write efficient code.', '编写高效的代码。'),
    ('Code Performance', '代码性能'),
    ('Optimize code performance.', '优化代码性能。'),
    ('Code Reliability', '代码可靠性'),
    ('Write reliable code.', '编写可靠的代码。'),
    ('Code Stability', '代码稳定性'),
    ('Ensure code stability.', '确保代码稳定性。'),
    ('Code Robustness', '代码健壮性'),
    ('Write robust code.', '编写健壮的代码。'),
    ('Code Flexibility', '代码灵活性'),
    ('Write flexible code.', '编写灵活的代码。'),
    ('Code Maintainability', '代码可维护性'),
    ('Write maintainable code.', '编写可维护的代码。'),
    ('Code Extensibility', '代码可扩展性'),
    ('Write extensible code.', '编写可扩展的代码。'),
    ('Code Testability', '代码可测试性'),
    ('Write testable code.', '编写可测试的代码。'),
    ('Code Debugging', '代码调试'),
    ('Debug your code effectively.', '有效调试您的代码。'),
    ('Code Profiling', '代码性能分析'),
    ('Profile your code for performance.', '对代码进行性能分析。'),
    ('Code Monitoring', '代码监控'),
    ('Monitor your code for issues.', '监控您的代码问题。'),
    ('Code Logging', '代码日志'),
    ('Log your code appropriately.', '适当记录您的代码。'),
    ('Code Error Handling', '代码错误处理'),
    ('Handle errors in your code.', '处理代码中的错误。'),
    ('Code Exception Handling', '代码异常处理'),
    ('Handle exceptions in your code.', '处理代码中的异常。'),
    ('Code Error Recovery', '代码错误恢复'),
    ('Recover from errors in your code.', '从代码错误中恢复。'),
    ('Code Failure Handling', '代码故障处理'),
    ('Handle failures in your code.', '处理代码中的故障。'),
    ('Code Crash Handling', '代码崩溃处理'),
    ('Handle crashes in your code.', '处理代码中的崩溃。'),
    ('Code Timeout Handling', '代码超时处理'),
    ('Handle timeouts in your code.', '处理代码中的超时。'),
    ('Code Resource Management', '代码资源管理'),
    ('Manage resources in your code.', '管理代码中的资源。'),
    ('Memory Leak Prevention', '内存泄漏预防'),
    ('Prevent memory leaks in your code.', '防止代码中的内存泄漏。'),
    ('Resource Cleanup', '资源清理'),
    ('Clean up resources in your code.', '清理代码中的资源。'),
    ('Resource Disposal', '资源释放'),
    ('Dispose of resources properly.', '正确释放资源。'),
    ('Resource Management', '资源管理'),
    ('Manage resources effectively.', '有效管理资源。'),
    ('Resource Allocation', '资源分配'),
    ('Allocate resources efficiently.', '高效分配资源。'),
    ('Resource Deallocation', '资源释放'),
    ('Deallocate resources properly.', '正确释放资源。'),
    ('Resource Optimization', '资源优化'),
    ('Optimize resource usage.', '优化资源使用。'),
    ('Resource Utilization', '资源利用率'),
    ('Utilize resources efficiently.', '高效利用资源。'),
    ('Resource Efficiency', '资源效率'),
    ('Use resources efficiently.', '高效使用资源。'),
    ('Resource Conservation', '资源节约'),
    ('Conserve resources in your code.', '在代码中节约资源。'),
    ('Resource Preservation', '资源保护'),
    ('Preserve resources in your code.', '在代码中保护资源。'),
    ('Resource Protection', '资源保护'),
    ('Protect resources in your code.', '保护代码中的资源。'),
    ('Resource Security', '资源安全'),
    ('Secure resources in your code.', '保护代码中的资源安全。'),
    ('Resource Integrity', '资源完整性'),
    ('Maintain resource integrity.', '维护资源完整性。'),
    ('Resource Consistency', '资源一致性'),
    ('Maintain resource consistency.', '维护资源一致性。'),
    ('Resource Reliability', '资源可靠性'),
    ('Ensure resource reliability.', '确保资源可靠性。'),
    ('Resource Availability', '资源可用性'),
    ('Ensure resource availability.', '确保资源可用性。'),
    ('Resource Accessibility', '资源可访问性'),
    ('Ensure resource accessibility.', '确保资源可访问性。'),
    ('Resource Usability', '资源可用性'),
    ('Ensure resource usability.', '确保资源可用性。'),
    ('Resource Functionality', '资源功能'),
    ('Ensure resource functionality.', '确保资源功能。'),
    ('Resource Features', '资源特性'),
    ('Utilize resource features.', '利用资源特性。'),
    ('Resource Capabilities', '资源能力'),
    ('Leverage resource capabilities.', '利用资源能力。'),
    ('Resource Potential', '资源潜力'),
    ('Maximize resource potential.', '最大化资源潜力。'),
    ('Resource Value', '资源价值'),
    ('Extract resource value.', '提取资源价值。'),
    ('Resource Benefit', '资源收益'),
    ('Realize resource benefits.', '实现资源收益。'),
    ('Resource Advantage', '资源优势'),
    ('Leverage resource advantages.', '利用资源优势。'),
    ('Resource Opportunity', '资源机会'),
    ('Seize resource opportunities.', '抓住资源机会。'),
    ('Resource Challenge', '资源挑战'),
    ('Address resource challenges.', '应对资源挑战。'),
    ('Resource Risk', '资源风险'),
    ('Mitigate resource risks.', '降低资源风险。'),
    ('Resource Threat', '资源威胁'),
    ('Counter resource threats.', '对抗资源威胁。'),
    ('Resource Vulnerability', '资源脆弱性'),
    ('Address resource vulnerabilities.', '应对资源脆弱性。'),
    ('Resource Exposure', '资源暴露'),
    ('Minimize resource exposure.', '最小化资源暴露。'),
    ('Resource Impact', '资源影响'),
    ('Assess resource impact.', '评估资源影响。'),
    ('Resource Consequence', '资源后果'),
    ('Manage resource consequences.', '管理资源后果。'),
    ('Resource Outcome', '资源结果'),
    ('Optimize resource outcomes.', '优化资源结果。'),
    ('Resource Result', '资源结果'),
    ('Achieve resource results.', '实现资源结果。'),
    ('Resource Output', '资源输出'),
    ('Maximize resource output.', '最大化资源输出。'),
    ('Resource Yield', '资源产出'),
    ('Increase resource yield.', '提高资源产出。'),
    ('Resource Return', '资源回报'),
    ('Maximize resource return.', '最大化资源回报。'),
    ('Resource Reward', '资源回报'),
    ('Earn resource rewards.', '赚取资源回报。'),
    ('Resource Gain', '资源收益'),
    ('Realize resource gains.', '实现资源收益。'),
    ('Resource Profit', '资源利润'),
    ('Generate resource profit.', '产生资源利润。'),
    ('Resource Income', '资源收入'),
    ('Increase resource income.', '增加资源收入。'),
    ('Resource Revenue', '资源收入'),
    ('Maximize resource revenue.', '最大化资源收入。'),
    ('Resource Earnings', '资源收益'),
    ('Boost resource earnings.', '提升资源收益。'),
    ('Resource Proceeds', '资源收益'),
    ('Collect resource proceeds.', '收集资源收益。'),
    ('Resource Receipts', '资源收入'),
    ('Track resource receipts.', '跟踪资源收入。'),
    ('Resource Inflow', '资源流入'),
    ('Monitor resource inflow.', '监控资源流入。'),
    ('Resource Influx', '资源涌入'),
    ('Manage resource influx.', '管理资源涌入。'),
    ('Resource Injection', '资源注入'),
    ('Control resource injection.', '控制资源注入。'),
    ('Resource Input', '资源输入'),
    ('Process resource input.', '处理资源输入。'),
    ('Resource Supply', '资源供应'),
    ('Ensure resource supply.', '确保资源供应。'),
    ('Resource Provision', '资源提供'),
    ('Provide resource provisions.', '提供资源供给。'),
    ('Resource Provisioning', '资源供应'),
    ('Complete resource provisioning.', '完成资源供应。'),
    ('Resource Preparation', '资源准备'),
    ('Prepare resources adequately.', '充分准备资源。'),
    ('Resource Readiness', '资源就绪'),
    ('Ensure resource readiness.', '确保资源就绪。'),
    ('Resource Availability', '资源可用性'),
    ('Confirm resource availability.', '确认资源可用性。'),
    ('Resource Access', '资源访问'),
    ('Grant resource access.', '授予资源访问权限。'),
    ('Resource Permission', '资源权限'),
    ('Set resource permissions.', '设置资源权限。'),
    ('Resource Authorization', '资源授权'),
    ('Authorize resource access.', '授权资源访问。'),
    ('Resource Authentication', '资源认证'),
    ('Authenticate resource access.', '认证资源访问。'),
    ('Resource Verification', '资源验证'),
    ('Verify resource access.', '验证资源访问。'),
    ('Resource Validation', '资源验证'),
    ('Validate resource access.', '验证资源访问。'),
    ('Resource Confirmation', '资源确认'),
    ('Confirm resource access.', '确认资源访问。'),
    ('Resource Approval', '资源批准'),
    ('Approve resource access.', '批准资源访问。'),
    ('Resource Endorsement', '资源认可'),
    ('Endorse resource access.', '认可资源访问。'),
    ('Resource Recommendation', '资源推荐'),
    ('Recommend resource access.', '推荐资源访问。'),
    ('Resource Suggestion', '资源建议'),
    ('Suggest resource access.', '建议资源访问。'),
    ('Resource Advice', '资源建议'),
    ('Advise on resource access.', '就资源访问提供建议。'),
    ('Resource Guidance', '资源指导'),
    ('Guide resource access.', '指导资源访问。'),
    ('Resource Direction', '资源方向'),
    ('Direct resource access.', '指导资源访问。'),
    ('Resource Instruction', '资源指令'),
    ('Instruct resource access.', '指示资源访问。'),
    ('Resource Command', '资源命令'),
    ('Command resource access.', '命令资源访问。'),
    ('Resource Order', '资源命令'),
    ('Order resource access.', '命令资源访问。'),
    ('Resource Request', '资源请求'),
    ('Request resource access.', '请求资源访问。'),
    ('Resource Inquiry', '资源查询'),
    ('Inquire about resource access.', '查询资源访问。'),
    ('Resource Question', '资源问题'),
    ('Question resource access.', '质疑资源访问。'),
    ('Resource Query', '资源查询'),
    ('Query resource access.', '查询资源访问。'),
    ('Resource Search', '资源搜索'),
    ('Search for resources.', '搜索资源。'),
    ('Resource Discovery', '资源发现'),
    ('Discover resources.', '发现资源。'),
    ('Resource Exploration', '资源探索'),
    ('Explore resources.', '探索资源。'),
    ('Resource Investigation', '资源调查'),
    ('Investigate resources.', '调查资源。'),
    ('Resource Examination', '资源检查'),
    ('Examine resources.', '检查资源。'),
    ('Resource Inspection', '资源检查'),
    ('Inspect resources.', '检查资源。'),
    ('Resource Review', '资源审查'),
    ('Review resources.', '审查资源。'),
    ('Resource Audit', '资源审计'),
    ('Audit resources.', '审计资源。'),
    ('Resource Assessment', '资源评估'),
    ('Assess resources.', '评估资源。'),
    ('Resource Evaluation', '资源评价'),
    ('Evaluate resources.', '评价资源。'),
    ('Resource Analysis', '资源分析'),
    ('Analyze resources.', '分析资源。'),
    ('Resource Study', '资源研究'),
    ('Study resources.', '研究资源。'),
    ('Resource Research', '资源研究'),
    ('Research resources.', '研究资源。'),
    ('Resource Investigation', '资源调查'),
    ('Investigate resources.', '调查资源。'),
    ('Resource Inquiry', '资源查询'),
    ('Inquire about resources.', '查询资源。'),
    ('Resource Questioning', '资源质疑'),
    ('Question resources.', '质疑资源。'),
    ('Resource Challenging', '资源挑战'),
    ('Challenge resources.', '挑战资源。'),
    ('Resource Testing', '资源测试'),
    ('Test resources.', '测试资源。'),
    ('Resource Validation', '资源验证'),
    ('Validate resources.', '验证资源。'),
    ('Resource Verification', '资源验证'),
    ('Verify resources.', '验证资源。'),
    ('Resource Confirmation', '资源确认'),
    ('Confirm resources.', '确认资源。'),
    ('Resource Certification', '资源认证'),
    ('Certify resources.', '认证资源。'),
    ('Resource Accreditation', '资源认可'),
    ('Accredit resources.', '认可资源。'),
    ('Resource Authorization', '资源授权'),
    ('Authorize resources.', '授权资源。'),
    ('Resource Permission', '资源权限'),
    ('Permit resource access.', '允许资源访问。'),
    ('Resource Allowance', '资源许可'),
    ('Allow resource access.', '允许资源访问。'),
    ('Resource Clearance', '资源许可'),
    ('Clear resource access.', '清除资源访问。'),
    ('Resource Approval', '资源批准'),
    ('Approve resources.', '批准资源。'),
    ('Resource Endorsement', '资源认可'),
    ('Endorse resources.', '认可资源。'),
    ('Resource Support', '资源支持'),
    ('Support resources.', '支持资源。'),
    ('Resource Assistance', '资源协助'),
    ('Assist with resources.', '协助资源。'),
    ('Resource Help', '资源帮助'),
    ('Help with resources.', '帮助资源。'),
    ('Resource Aid', '资源援助'),
    ('Aid resources.', '援助资源。'),
    ('Resource Service', '资源服务'),
    ('Service resources.', '服务资源。'),
    ('Resource Care', '资源关怀'),
    ('Care for resources.', '关怀资源。'),
    ('Resource Attention', '资源关注'),
    ('Attend to resources.', '关注资源。'),
    ('Resource Consideration', '资源考虑'),
    ('Consider resources.', '考虑资源。'),
    ('Resource Thought', '资源思考'),
    ('Think about resources.', '思考资源。'),
    ('Resource Reflection', '资源反思'),
    ('Reflect on resources.', '反思资源。'),
    ('Resource Meditation', '资源冥想'),
    ('Meditate on resources.', '冥想资源。'),
    ('Resource Contemplation', '资源沉思'),
    ('Contemplate resources.', '沉思资源。'),
    ('Resource Pondering', '资源深思'),
    ('Ponder resources.', '深思资源。'),
    ('Resource Deliberation', '资源斟酌'),
    ('Deliberate on resources.', '斟酌资源。'),
    ('Resource Consideration', '资源考虑'),
    ('Consider resources carefully.', '仔细考虑资源。'),
    ('Resource Examination', '资源检查'),
    ('Examine resources carefully.', '仔细检查资源。'),
    ('Resource Inspection', '资源检查'),
    ('Inspect resources carefully.', '仔细检查资源。'),
    ('Resource Review', '资源审查'),
    ('Review resources carefully.', '仔细审查资源。'),
    ('Resource Analysis', '资源分析'),
    ('Analyze resources carefully.', '仔细分析资源。'),
    ('Resource Study', '资源研究'),
    ('Study resources carefully.', '仔细研究资源。'),
    ('Resource Research', '资源研究'),
    ('Research resources carefully.', '仔细研究资源。'),
]

def translate_file(path):
    with open(path, 'r') as f:
        text = f.read()
    orig = text
    for en, zh in REPLACEMENTS:
        text = text.replace(en, zh)
    if text != orig:
        with open(path, 'w') as f:
            f.write(text)
        return True
    return False

def main():
    count = 0
    for root, dirs, files in os.walk(BASE):
        for fn in files:
            if fn == 'index.md':
                path = os.path.join(root, fn)
                if translate_file(path):
                    count += 1
    print(f'Translated {count} files')

if __name__ == '__main__':
    main()
