#!/usr/bin/env python3
"""Batch translate remaining API docs pages."""
import os, re, glob

BASE = '/home/bestony/code/garmin-docs/docs/zh/connect-iq/api-docs'

# Common English->Chinese replacements for API doc prose
REPLACEMENTS = {
    # Module/class overview patterns
    'The Communications Module provides tools for communication.': '通信模块提供通信工具。',
    'The Activity Recording module will allow Apps to access the FIT file recording capabilities of the device.': '活动录制模块允许应用访问设备的 FIT 文件录制功能。',
    'The Math Module provides various math methods available for use by Apps.': 'Math 模块提供各种可供应用使用的数学方法。',
    'The UserProfile module will allow apps to access user information.': 'UserProfile 模块允许应用访问用户信息。',
    'The Info class contains information about the current activity.': 'Info 类包含当前活动的信息。',
    'AppBase is the base class for an app.': 'AppBase 是应用的基类。',
    'The Background module provides background event handling.': 'Background 模块提供后台事件处理。',
    'The System module provides system-level services.': 'System 模块提供系统级服务。',
    'The Application module provides application management.': 'Application 模块提供应用管理。',
    'The WatchUi module provides user interface components.': 'WatchUi 模块提供用户界面组件。',
    'The Toybox module provides core functionality.': 'Toybox 模块提供核心功能。',
    'The Graphics module provides drawing capabilities.': 'Graphics 模块提供绘图功能。',
    'The Lang module provides language utilities.': 'Lang 模块提供语言工具。',
    'The Sensor module provides sensor data access.': 'Sensor 模块提供传感器数据访问。',
    'The Activity module provides activity data access.': 'Activity 模块提供活动数据访问。',
    'The Ant module provides ANT+ protocol support.': 'Ant 模块提供 ANT+ 协议支持。',
    'The AntPlus module provides ANT+ device support.': 'AntPlus 模块提供 ANT+ 设备支持。',
    'The BluetoothLowEnergy module provides BLE support.': 'BluetoothLowEnergy 模块提供 BLE 支持。',
    'The Media module provides media playback capabilities.': 'Media 模块提供媒体播放功能。',
    'The Complications module provides complication data.': 'Complications 模块提供复杂功能数据。',
    'The Position module provides location data.': 'Position 模块提供位置数据。',
    'The Weather module provides weather data.': 'Weather 模块提供天气数据。',
    'The Attention module provides attention-indicator drawing.': 'Attention 模块提供注意力指示器绘图。',
    'The Timer module provides timer functionality.': 'Timer 模块提供计时器功能。',
    'The Cryptography module provides cryptographic functions.': 'Cryptography 模块提供加密功能。',
    'The PersistedContent module provides persisted content access.': 'PersistedContent 模块提供持久化内容访问。',
    'The StringUtil module provides string utilities.': 'StringUtil 模块提供字符串工具。',
    'The Time module provides time utilities.': 'Time 模块提供时间工具。',
    'The System module provides system-level services and device information.': 'System 模块提供系统级服务和设备信息。',
    'The View class provides the base class for all views.': 'View 类提供所有视图的基类。',
    'The Drawable class provides drawing capabilities.': 'Drawable 类提供绘图功能。',
    'The InputDelegate class handles user input.': 'InputDelegate 类处理用户输入。',
    'The Menu class provides a menu interface.': 'Menu 类提供菜单界面。',
    'The Button class provides a button interface.': 'Button 类提供按钮界面。',
    'The Font class provides font rendering.': 'Font 类提供字体渲染。',
    'The Bitmap class provides bitmap rendering.': 'Bitmap 类提供位图渲染。',
    'The Layer class provides a drawing layer.': 'Layer 类提供绘图层。',
    'The AnimationDelegate class handles animations.': 'AnimationDelegate 类处理动画。',
    'The WatchFace class provides watch face functionality.': 'WatchFace 类提供手表表面功能。',
    'The WatchFaceDelegate class handles watch face events.': 'WatchFaceDelegate 类处理手表表面事件。',
    'The Menu2 class provides a menu interface.': 'Menu2 类提供菜单界面。',
    'The CustomMenu class provides a custom menu interface.': 'CustomMenu 类提供自定义菜单界面。',
    'The ToggleMenuItem class provides a toggle menu item.': 'ToggleMenuItem 类提供切换菜单项。',
    'The MenuItem class provides a menu item.': 'MenuItem 类提供菜单项。',
    'The CustomMenuItem class provides a custom menu item.': 'CustomMenuItem 类提供自定义菜单项。',
    'The MapView class provides a map view.': 'MapView 类提供地图视图。',
    'The DataField class provides data field functionality.': 'DataField 类提供数据字段功能。',
    'The ServiceDelegate class handles service events.': 'ServiceDelegate 类处理服务事件。',
    'The BleDelegate class handles BLE events.': 'BleDelegate 类处理 BLE 事件。',
    'The Profile class provides user profile data.': 'Profile 类提供用户资料数据。',
    'The UserActivity class provides user activity data.': 'UserActivity 类提供用户活动数据。',
    'The Session class provides activity session data.': 'Session 类提供活动会话数据。',
    'The Info class provides activity info data.': 'Info 类提供活动信息数据。',
    'The Device class provides BLE device data.': 'Device 类提供 BLE 设备数据。',
    'The Characteristic class provides BLE characteristic data.': 'Characteristic 类提供 BLE 特性数据。',
    'The ScanResult class provides BLE scan results.': 'ScanResult 类提供 BLE 扫描结果。',
    'The DevicePairException class provides device pair exception data.': 'DevicePairException 类提供设备配对异常数据。',
    'The InvalidRequestException class provides invalid request exception data.': 'InvalidRequestException 类提供无效请求异常数据。',
    'The UuidFormatException class provides UUID format exception data.': 'UuidFormatException 类提供 UUID 格式异常数据。',
    'The ProfileRegistrationException class provides profile registration exception data.': 'ProfileRegistrationException 类提供配置文件注册异常数据。',
    'The ExitDataSizeLimitException class provides exit data size limit exception data.': 'ExitDataSizeLimitException 类提供退出数据大小限制异常数据。',
    'The MessageSizeLimitException class provides message size limit exception data.': 'MessageSizeLimitException 类提供消息大小限制异常数据。',
    'The AntPlusNotAllowedException class provides ANT+ not allowed exception data.': 'AntPlusNotAllowedException 类提供 ANT+ 不允许异常数据。',
    'The BikeSpeedInfo class provides bike speed info data.': 'BikeSpeedInfo 类提供自行车速度信息数据。',
    'The BikeCadenceInfo class provides bike cadence info data.': 'BikeCadenceInfo 类提供自行车踏频信息数据。',
    'The ShiftingListener class provides shifting listener data.': 'ShiftingListener 类提供变速监听器数据。',
    'The LightNetwork class provides light network data.': 'LightNetwork 类提供灯光网络数据。',
    'The VectorFont class provides vector font data.': 'VectorFont 类提供矢量字体数据。',
    'The BufferedBitmap class provides buffered bitmap data.': 'BufferedBitmap 类提供缓冲位图数据。',
    'The BoundingBox class provides bounding box data.': 'BoundingBox 类提供边界框数据。',
    'The AffineTransform class provides affine transform data.': 'AffineTransform 类提供仿射变换数据。',
    'The Key class provides cryptographic key data.': 'Key 类提供加密密钥数据。',
    'The Cipher class provides cryptographic cipher data.': 'Cipher 类提供加密密码数据。',
    'The Dictionary class provides dictionary data.': 'Dictionary 类提供字典数据。',
    'The Array class provides array data.': 'Array 类提供数组数据。',
    'The ByteArray class provides byte array data.': 'ByteArray 类提供字节数组数据。',
    'The String class provides string data.': 'String 类提供字符串数据。',
    'The Number class provides number data.': 'Number 类提供数字数据。',
    'The Boolean class provides boolean data.': 'Boolean 类提供布尔数据。',
    'The Object class provides object data.': 'Object 类提供对象数据。',
    'The Lang class provides language utilities.': 'Lang 类提供语言工具。',
    'The Moment class provides time moment data.': 'Moment 类提供时间时刻数据。',
    'The Gregorian class provides Gregorian calendar data.': 'Gregorian 类提供公历数据。',
    'The Duration class provides duration data.': 'Duration 类提供持续时间数据。',
    'The LocalMoment class provides local moment data.': 'LocalMoment 类提供本地时刻数据。',
    'The Stats class provides system stats data.': 'Stats 类提供系统统计数据显示。',
    'The DeviceSettings class provides device settings data.': 'DeviceSettings 类提供设备设置数据。',
    'The ConnectionInfo class provides connection info data.': 'ConnectionInfo 类提供连接信息数据。',
    'The AppNotInstalledException class provides app not installed exception data.': 'AppNotInstalledException 类提供应用未安装异常数据。',
    'The InvalidKeyException class provides invalid key exception data.': 'InvalidKeyException 类提供无效密钥异常数据。',
    'The InvalidHexStringException class provides invalid hex string exception data.': 'InvalidHexStringException 类提供无效十六进制字符串异常数据。',
    'The StorageFullException class provides storage full exception data.': 'StorageFullException 类提供存储满异常数据。',
    'The ObjectStoreAccessException class provides object store access exception data.': 'ObjectStoreAccessException 类提供对象存储访问异常数据。',
    'The InvalidPointException class provides invalid point exception data.': 'InvalidPointException 类提供无效点异常数据。',
    'The InvalidSelectableStateException class provides invalid selectable state exception data.': 'InvalidSelectableStateException 类提供无效可选择状态异常数据。',
    'The InvalidMenuItemTypeException class provides invalid menu item type exception data.': 'InvalidMenuItemTypeException 类提供无效菜单项类型异常数据。',
    'The ReviewResponseToken class provides review response token data.': 'ReviewResponseToken 类提供审查响应令牌数据。',
    'The AssertException class provides assert exception data.': 'AssertException 类提供断言异常数据。',
    'The RealTimeClockNotValidException class provides real-time clock not valid exception data.': 'RealTimeClockNotValidException 类提供实时时钟无效异常数据。',
    'The Message class provides message data.': 'Message 类提供消息数据。',
    'The PhoneAppMessage class provides phone app message data.': 'PhoneAppMessage 类提供手机应用消息数据。',
    'The OAuthMessage class provides OAuth message data.': 'OAuthMessage 类提供 OAuth 消息数据。',
    'The ConnectionListener class provides connection listener data.': 'ConnectionListener 类提供连接监听器数据。',
    'The MailboxIterator class provides mailbox iterator data.': 'MailboxIterator 类提供邮箱迭代器数据。',
    'The SyncDelegate class provides sync delegate data.': 'SyncDelegate 类提供同步委托数据。',
    'The OAuthMessage class provides OAuth message data.': 'OAuthMessage 类提供 OAuth 消息数据。',
    'The Route class provides route data.': 'Route 类提供路线数据。',
    'The Track class provides track data.': 'Track 类提供轨迹数据。',
    'The Course class provides course data.': 'Course 类提供路线数据。',
    'The Workout class provides workout data.': 'Workout 类提供训练数据。',
    'The Waypoint class provides waypoint data.': 'Waypoint 类提供航点数据。',
    'The ContentDelegate class provides content delegate data.': 'ContentDelegate 类提供内容委托数据。',
    'The ContentIterator class provides content iterator data.': 'ContentIterator 类提供内容迭代器数据。',
    'The PlaybackProfile class provides playback profile data.': 'PlaybackProfile 类提供播放配置文件数据。',
    'The DeviceConfig class provides device config data.': 'DeviceConfig 类提供设备配置数据。',
    'The GenericChannel class provides generic channel data.': 'GenericChannel 类提供通用通道数据。',
    'The FitnessEquipment class provides fitness equipment data.': 'FitnessEquipment 类提供健身器材数据。',
    'The AntDevice class provides ANT device data.': 'AntDevice 类提供 ANT 设备数据。',
    'The AntPlusDevice class provides ANT+ device data.': 'AntPlusDevice 类提供 ANT+ 设备数据。',
    'The EncryptionInvalidSettingsException class provides encryption invalid settings exception data.': 'EncryptionInvalidSettingsException 类提供加密无效设置异常数据。',
    'The UnableToAcquireChannelException class provides unable to acquire channel exception data.': 'UnableToAcquireChannelException 类提供无法获取通道异常数据。',
    'The InvalidBlockSizeException class provides invalid block size exception data.': 'InvalidBlockSizeException 类提供无效块大小异常数据。',
    'The InvalidPaletteException class provides invalid palette exception data.': 'InvalidPaletteException 类提供无效调色板异常数据。',
    'The InvalidBitmapResourceException class provides invalid bitmap resource exception data.': 'InvalidBitmapResourceException 类提供无效位图资源异常数据。',
    'The FontReference class provides font reference data.': 'FontReference 类提供字体引用数据。',
    'The TooManySensorDataListenersException class provides too many sensor data listeners exception data.': 'TooManySensorDataListenersException 类提供过多传感器数据监听器异常数据。',
    'The SensorInfo class provides sensor info data.': 'SensorInfo 类提供传感器信息数据。',
    'The CurrentConditions class provides current conditions data.': 'CurrentConditions 类提供当前状况数据。',
    'The Attention class provides attention data.': 'Attention 类提供注意力数据。',
    'The Position class provides position data.': 'Position 类提供位置数据。',
    'The ActivityMonitor class provides activity monitor data.': 'ActivityMonitor 类提供活动监测数据。',
    'The ComplicationNotFoundException class provides complication not found exception data.': 'ComplicationNotFoundException 类提供复杂功能未找到异常数据。',
    'The Iterator class provides iterator data.': 'Iterator 类提供迭代器数据。',
    'The Storage class provides storage data.': 'Storage 类提供存储数据。',
    'The Properties class provides properties data.': 'Properties 类提供属性数据。',
    'PersistedContent class provides persisted content data.': 'PersistedContent 类提供持久化内容数据。',
    'The Application module provides application management.': 'Application 模块提供应用管理。',
    'The Background module provides background event handling.': 'Background 模块提供后台事件处理。',
    'The System module provides system-level services.': 'System 模块提供系统级服务。',
    'The Application module provides application lifecycle management.': 'Application 模块提供应用生命周期管理。',
    'The System module provides system-level services and device information.': 'System 模块提供系统级服务和设备信息。',
    'The Toybox module provides core API functionality.': 'Toybox 模块提供核心 API 功能。',
    'The WatchUi module provides user interface components for watch apps.': 'WatchUi 模块提供手表应用的用户界面组件。',
    'The Graphics module provides 2D drawing capabilities.': 'Graphics 模块提供 2D 绘图功能。',
    'The Graphics module provides drawing capabilities.': 'Graphics 模块提供绘图功能。',
    'The Lang module provides language utilities and data types.': 'Lang 模块提供语言工具和数据类型。',
    'The Math module provides mathematical functions.': 'Math 模块提供数学函数。',
    'The Time module provides time and date utilities.': 'Time 模块提供时间和日期工具。',
    'The Media module provides media playback and recording capabilities.': 'Media 模块提供媒体播放和录制功能。',
    'The Sensor module provides sensor data access.': 'Sensor 模块提供传感器数据访问。',
    'The Activity module provides activity data access.': 'Activity 模块提供活动数据访问。',
    'The UserProfile module provides user profile data access.': 'UserProfile 模块提供用户资料数据访问。',
    'The Communications module provides communication capabilities.': 'Communications 模块提供通信功能。',
    'The BluetoothLowEnergy module provides Bluetooth Low Energy support.': 'BluetoothLowEnergy 模块提供蓝牙低功耗支持。',
    'The Ant module provides ANT protocol support.': 'Ant 模块提供 ANT 协议支持。',
    'The AntPlus module provides ANT+ device support.': 'AntPlus 模块提供 ANT+ 设备支持。',
    'The PersistedContent module provides persisted content access.': 'PersistedContent 模块提供持久化内容访问。',
    'The StringUtil module provides string utility functions.': 'StringUtil 模块提供字符串工具函数。',
    'The Cryptography module provides cryptographic functions.': 'Cryptography 模块提供加密功能。',
    'The Attention module provides attention-indicator drawing.': 'Attention 模块提供注意力指示器绘图。',
    'The Timer module provides timer functionality.': 'Timer 模块提供计时器功能。',
    'The Position module provides location and positioning data.': 'Position 模块提供位置和定位数据。',
    'The Weather module provides weather data access.': 'Weather 模块提供天气数据访问。',
    'The Complications module provides complication data access.': 'Complications 模块提供复杂功能数据访问。',
    'The ActivityRecording module provides activity recording capabilities.': 'ActivityRecording 模块提供活动录制功能。',
    'The DeviceSettings class provides device settings access.': 'DeviceSettings 类提供设备设置访问。',
    'The View class provides the base view functionality.': 'View 类提供基础视图功能。',
    'The Drawable class provides drawable functionality.': 'Drawable 类提供可绘制功能。',
    'The InputDelegate class handles input events.': 'InputDelegate 类处理输入事件。',
    'The Menu class provides menu functionality.': 'Menu 类提供菜单功能。',
    'The Button class provides button functionality.': 'Button 类提供按钮功能。',
    'The Font class provides font functionality.': 'Font 类提供字体功能。',
    'The Bitmap class provides bitmap functionality.': 'Bitmap 类提供位图功能。',
    'The Layer class provides layer functionality.': 'Layer 类提供层功能。',
    'The AnimationDelegate class handles animation events.': 'AnimationDelegate 类处理动画事件。',
    'The WatchFace class provides watch face functionality.': 'WatchFace 类提供手表表面功能。',
    'The WatchFaceDelegate class handles watch face events.': 'WatchFaceDelegate 类处理手表表面事件。',
    'The Menu2 class provides menu functionality.': 'Menu2 类提供菜单功能。',
    'The CustomMenu class provides custom menu functionality.': 'CustomMenu 类提供自定义菜单功能。',
    'The ToggleMenuItem class provides toggle menu item functionality.': 'ToggleMenuItem 类提供切换菜单项功能。',
    'The MenuItem class provides menu item functionality.': 'MenuItem 类提供菜单项功能。',
    'The CustomMenuItem class provides custom menu item functionality.': 'CustomMenuItem 类提供自定义菜单项功能。',
    'The MapView class provides map view functionality.': 'MapView 类提供地图视图功能。',
    'The DataField class provides data field functionality.': 'DataField 类提供数据字段功能。',
    'The ServiceDelegate class handles service events.': 'ServiceDelegate 类处理服务事件。',
    'The BleDelegate class handles BLE events.': 'BleDelegate 类处理 BLE 事件。',
    'The Profile class provides profile functionality.': 'Profile 类提供资料功能。',
    'The UserActivity class provides user activity functionality.': 'UserActivity 类提供用户活动功能。',
    'The Session class provides session functionality.': 'Session 类提供会话功能。',
    'The Info class provides info functionality.': 'Info 类提供信息功能。',
    'The Device class provides device functionality.': 'Device 类提供设备功能。',
    'The Characteristic class provides characteristic functionality.': 'Characteristic 类提供特性功能。',
    'The ScanResult class provides scan result functionality.': 'ScanResult 类提供扫描结果功能。',
    'The Key class provides key functionality.': 'Key 类提供密钥功能。',
    'The Cipher class provides cipher functionality.': 'Cipher 类提供密码功能。',
    'The Dictionary class provides dictionary functionality.': 'Dictionary 类提供字典功能。',
    'The Array class provides array functionality.': 'Array 类提供数组功能。',
    'The ByteArray class provides byte array functionality.': 'ByteArray 类提供字节数组功能。',
    'The String class provides string functionality.': 'String 类提供字符串功能。',
    'The Number class provides number functionality.': 'Number 类提供数字功能。',
    'The Boolean class provides boolean functionality.': 'Boolean 类提供布尔功能。',
    'The Object class provides object functionality.': 'Object 类提供对象功能。',
    'The Lang class provides language functionality.': 'Lang 类提供语言功能。',
    'The Moment class provides moment functionality.': 'Moment 类提供时刻功能。',
    'The Gregorian class provides Gregorian calendar functionality.': 'Gregorian 类提供公历功能。',
    'The Duration class provides duration functionality.': 'Duration 类提供持续时间功能。',
    'The LocalMoment class provides local moment functionality.': 'LocalMoment 类提供本地时刻功能。',
    'The Stats class provides stats functionality.': 'Stats 类提供统计功能。',
    'The Route class provides route functionality.': 'Route 类提供路线功能。',
    'The Track class provides track functionality.': 'Track 类提供轨迹功能。',
    'The Course class provides course functionality.': 'Course 类提供路线功能。',
    'The Workout class provides workout functionality.': 'Workout 类提供训练功能。',
    'The Waypoint class provides waypoint functionality.': 'Waypoint 类提供航点功能。',
    'The ContentDelegate class provides content delegate functionality.': 'ContentDelegate 类提供内容委托功能。',
    'The ContentIterator class provides content iterator functionality.': 'ContentIterator 类提供内容迭代器功能。',
    'The PlaybackProfile class provides playback profile functionality.': 'PlaybackProfile 类提供播放配置文件功能。',
    'The DeviceConfig class provides device config functionality.': 'DeviceConfig 类提供设备配置功能。',
    'The GenericChannel class provides generic channel functionality.': 'GenericChannel 类提供通用通道功能。',
    'The FitnessEquipment class provides fitness equipment functionality.': 'FitnessEquipment 类提供健身器材功能。',
    'The AntDevice class provides ANT device functionality.': 'AntDevice 类提供 ANT 设备功能。',
    'The AntPlusDevice class provides ANT+ device functionality.': 'AntPlusDevice 类提供 ANT+ 设备功能。',
    'The EncryptionInvalidSettingsException class provides encryption invalid settings exception functionality.': 'EncryptionInvalidSettingsException 类提供加密无效设置异常功能。',
    'The UnableToAcquireChannelException class provides unable to acquire channel exception functionality.': 'UnableToAcquireChannelException 类提供无法获取通道异常功能。',
    'The InvalidBlockSizeException class provides invalid block size exception functionality.': 'InvalidBlockSizeException 类提供无效块大小异常功能。',
    'The InvalidPaletteException class provides invalid palette exception functionality.': 'InvalidPaletteException 类提供无效调色板异常功能。',
    'The InvalidBitmapResourceException class provides invalid bitmap resource exception functionality.': 'InvalidBitmapResourceException 类提供无效位图资源异常功能。',
    'The FontReference class provides font reference functionality.': 'FontReference 类提供字体引用功能。',
    'The TooManySensorDataListenersException class provides too many sensor data listeners exception functionality.': 'TooManySensorDataListenersException 类提供过多传感器数据监听器异常功能。',
    'The SensorInfo class provides sensor info functionality.': 'SensorInfo 类提供传感器信息功能。',
    'The CurrentConditions class provides current conditions functionality.': 'CurrentConditions 类提供当前状况功能。',
    'The Attention class provides attention functionality.': 'Attention 类提供注意力功能。',
    'The Position class provides position functionality.': 'Position 类提供位置功能。',
    'The ActivityMonitor class provides activity monitor functionality.': 'ActivityMonitor 类提供活动监测功能。',
    'The ComplicationNotFoundException class provides complication not found exception functionality.': 'ComplicationNotFoundException 类提供复杂功能未找到异常功能。',
    'The Iterator class provides iterator functionality.': 'Iterator 类提供迭代器功能。',
    'The Storage class provides storage functionality.': 'Storage 类提供存储功能。',
    'The Properties class provides properties functionality.': 'Properties 类提供属性功能。',
    'PersistedContent class provides persisted content functionality.': 'PersistedContent 类提供持久化内容功能。',
}

def translate_file(path):
    with open(path, 'r') as f:
        text = f.read()
    original = text
    for en, zh in REPLACEMENTS.items():
        text = text.replace(en, zh)
    if text != original:
        with open(path, 'w') as f:
            f.write(text)
        return True
    return False

def main():
    count = 0
    for root, dirs, files in os.walk(BASE):
        for fn in files:
            if fn == 'index.md':
                path = os.path.join(root, fn)
                if translate_file(path):
                    count += 1
                    print(f' translated: {path}')
    print(f'\nTotal translated: {count}')

if __name__ == '__main__':
    main()