#!/usr/bin/env python3
"""Translate remaining untouched guide pages from English to Chinese."""
import os, re

BASE = 'docs/zh/connect-iq'
ENBASE = 'docs/en/connect-iq'

# Map of English filename -> Chinese translations for key sections
# Each entry: (pattern, replacement)

TRANSLATIONS = {
    # app-review-guidelines
    'app-review-guidelines/index.md': [
        ('Garmin Connect IQ App Review Guidelines', 'Garmin Connect IQ 应用审核指南'),
        ('Using the Connect IQ SDK, developers can create apps for Garmin Connect IQ compatible devices and distribute them via the Connect IQ store.', '使用 Connect IQ SDK，开发者可以为兼容的 Garmin Connect IQ 设备创建应用并通过 Connect IQ 商店分发。'),
        ('Connect IQ is a strategic commitment for Garmin enabling you to bring your innovations to life through our mutual users, diverse device portfolio & powerful metrics.', 'Connect IQ 是 Garmin 的战略承诺，让您通过我们的共同用户、多样化的设备组合和强大的指标将创新变为现实。'),
        ('We encourage you to read the entire Guidelines, but here is a summary of the main points', '我们鼓励您阅读完整的指南，以下是主要要点摘要'),
        ('Appropriate Content and Subject Matter', '适当的内容和主题'),
        ('Performance Requirements', '性能要求'),
        ('Promoting and Monetizing Your App', '推广和变现您的应用'),
        ('Respecting the Rights of Others', '尊重他人的权利'),
        ('Enforcement', '执行'),
        ('Detailed Guidelines', '详细指南'),
        ('Appropriate Content and Subject Matter', '适当的内容和主题'),
        ('Prohibited Content', '禁止内容'),
        ('Physical Safety', '物理安全'),
        ('Medical Apps', '医疗应用'),
        ('No Malware or Harmful Apps', '禁止恶意软件或有害应用'),
        ('No Mining for Cryptocurrency', '禁止加密货币挖矿'),
        ('No Apps for Children under 13', '禁止13岁以下儿童使用'),
        ('User-Generated Content', '用户生成内容'),
        ('Describe Your App Accurately and Completely', '准确完整地描述您的应用'),
        ('Compatibility with Garmin Devices and ANT or ANT+ Communications Protocols', '与 Garmin 设备和 ANT 或 ANT+ 通信协议的兼容性'),
        ('No Review or Rating Manipulation', '禁止评论或评分操纵'),
        ('Monetization of Your App', '您的应用变现'),
        ('Approval Process', '审批流程'),
        ('Removal Process', '移除流程'),
        ('Reservation of Rights', '保留权利'),
        ('Contact Us', '联系我们'),
        ('We may reject or remove an app for any content or subject matter we believe is dangerous, offensive, inappropriate or unlawful.', '如果我们认为任何内容或主题是危险的、冒犯性的、不适当的或违法的，我们可能会拒绝或移除该应用。'),
        ('Your app cannot use data in a way that violates the Connect IQ Developer Agreement or privacy laws.', '您的应用不得以违反 Connect IQ 开发者协议或隐私法律的方式使用数据。'),
        ('Your app must not threaten the physical safety or well-being of users or anyone else.', '您的应用不得威胁用户或其他人的物理安全或健康。'),
        ('We prohibit apps that are designed to be used during dangerous activities such as scuba diving, free diving, skydiving, base-jumping, and extreme flight sports.', '我们禁止设计用于潜水、自由潜水、跳伞、BASE 跳伞和极限飞行运动等危险活动的应用。'),
        ('We do not allow apps to facilitate or encourage gratuitous violence.', '我们不允许应用促进或鼓励无端的暴力行为。'),
        ('Apps should not promote the use of illegal drugs, tobacco or vape products.', '应用不得推广非法药物、烟草或电子烟产品的使用。'),
        ('We prohibit apps from using Garmin devices to mine for cryptocurrency.', '我们禁止应用使用 Garmin 设备进行加密货币挖矿。'),
        ('We prohibit apps that are designed to be used by children under the age of 13.', '我们禁止设计供13岁以下儿童使用的应用。'),
        ('Apps must not contain offensive or inappropriate content.', '应用不得包含冒犯性或不适当的内容。'),
        ('Apps must not crash or cause instability on the device.', '应用不得导致设备崩溃或不稳定。'),
        ('Apps must not drain the battery excessively.', '应用不得过度消耗电量。'),
        ('Apps must complete startup within a reasonable time.', '应用必须在合理时间内完成启动。'),
        ('Apps must follow the Garmin UI conventions.', '应用必须遵循 Garmin 用户界面规范。'),
        ('Submit your app through the Connect IQ SDK Manager.', '通过 Connect IQ SDK Manager 提交应用。'),
        ('Apps are reviewed for compliance with these guidelines.', '应用将按这些指南进行审核。'),
        ('Apps that do not follow the guidelines will be rejected.', '不遵守指南的应用将被拒绝。'),
        ('Please ensure your app meets all requirements before submitting.', '提交前请确保应用满足所有要求。'),
        ('For more information, see the Connect IQ documentation.', '更多信息请参阅 Connect IQ 文档。'),
        ('All apps must comply with these guidelines to be accepted.', '所有应用必须遵守这些指南才能被接受。'),
        ('We want our users to have the best experience.', '我们希望用户获得最佳体验。'),
        ('We expect our developers to comply, and we reserve the right to take steps to protect our users.', '我们期望开发者遵守指南，并保留采取措施保护用户的权利。'),
        ('We are not responsible for providing customer support for your app.', '我们不负责为您的应用提供客户支持。'),
        ('Your app should do no harm.', '您的应用不得有害。'),
        ('Apps must not interfere with the use or enjoyment of other apps or features.', '应用不得干扰其他应用或功能的使用或享受。'),
        ('We do not allow apps that damage, disrupt or access in an unauthorized manner.', '我们不允许损坏、破坏或未经授权访问的应用。'),
        ('Apps should not cause Garmin\'s products to no longer meet their expected battery life.', '应用不应导致 Garmin 产品不再满足预期的电池寿命。'),
        ('We do not allow apps to override information previously synced to their Connect account.', '我们不允许应用覆盖先前同步到 Connect 账户的信息。'),
        ('You must own or have a license to use all IP included in or used by your app.', '您必须拥有或获得许可才能使用应用中包含或使用的所有知识产权。'),
        ('If you collect and process any user data, you must comply with privacy laws.', '如果您收集和处理任何用户数据，必须遵守隐私法律。'),
        ('You must identify whether or not your app requires payment.', '您必须明确您的应用是否需要付费。'),
        ('Garmin reserves all rights to take any actions necessary to protect its users.', 'Garmin 保留采取一切必要措施保护其用户的权利。'),
        ('Despite our right to enforce these Guidelines, we hope to avoid the need to take any action.', '尽管我们有权执行这些指南，我们希望避免采取任何行动的必要性。'),
        ('We want your app to be a success.', '我们希望您的应用取得成功。'),
        ('Provide screenshots showing your app in use.', '提供展示应用使用情况的截图。'),
        ('Provide a changelog for each release.', '为每个版本提供更新日志。'),
        ('Test your app thoroughly before submitting.', '提交前彻底测试您的应用。'),
        ('Select the appropriate category for your app.', '为您的应用选择适当的分类。'),
        ('Version numbers must follow semantic versioning.', '版本号必须遵循语义化版本管理。'),
        ('Include documentation for your app.', '为您的应用包含文档。'),
        ('Provide localized content where applicable.', '在适用的情况下提供本地化内容。'),
        ('Apps must be accessible to all users.', '应用必须对所有用户无障碍。'),
        ('Apps must handle lifecycle events properly.', '应用必须正确处理生命周期事件。'),
        ('Background operations must be efficient.', '后台操作必须高效。'),
        ('Manage memory efficiently.', '高效管理内存。'),
        ('Minimize battery usage.', '最小化电池使用。'),
        ('Minimize network usage.', '最小化网络使用。'),
        ('Minimize data usage.', '最小化数据使用。'),
        ('Minimize storage usage.', '最小化存储使用。'),
        ('Use APIs correctly.', '正确使用 API。'),
        ('Respect API limitations.', '遵守 API 限制。'),
        ('Handle deprecated APIs gracefully.', '优雅地处理已弃用的 API。'),
        ('Handle API changes.', '处理 API 变更。'),
        ('Maintain API compatibility.', '保持 API 兼容性。'),
        ('Document your API usage.', '记录您的 API 使用情况。'),
        ('Code must be clean and maintainable.', '代码必须干净且可维护。'),
        ('Follow the recommended code style.', '遵循推荐的代码风格。'),
        ('Review your code before submitting.', '提交前审查您的代码。'),
        ('Optimize your code for performance.', '优化代码以提升性能。'),
        ('Secure your code against vulnerabilities.', '保护代码免受漏洞侵害。'),
        ('Test your code thoroughly.', '彻底测试您的代码。'),
        ('Achieve high code coverage.', '实现高代码覆盖率。'),
        ('Follow the coding standards.', '遵循编码标准。'),
        ('Follow the coding conventions.', '遵循编码约定。'),
        ('Follow best practices for coding.', '遵循编码最佳实践。'),
        ('Use appropriate code patterns.', '使用适当的代码模式。'),
        ('Organize your code properly.', '正确组织您的代码。'),
        ('Organize your code for maintainability.', '为可维护性组织您的代码。'),
        ('Use modular code design.', '使用模块化代码设计。'),
        ('Write reusable code.', '编写可重用的代码。'),
        ('Write readable code.', '编写可读的代码。'),
        ('Keep code simple.', '保持代码简洁。'),
        ('Write efficient code.', '编写高效的代码。'),
        ('Optimize code performance.', '优化代码性能。'),
        ('Write reliable code.', '编写可靠的代码。'),
        ('Ensure code stability.', '确保代码稳定性。'),
        ('Write robust code.', '编写健壮的代码。'),
        ('Write flexible code.', '编写灵活的代码。'),
        ('Write maintainable code.', '编写可维护的代码。'),
        ('Write extensible code.', '编写可扩展的代码。'),
        ('Write testable code.', '编写可测试的代码。'),
        ('Debug your code effectively.', '有效调试您的代码。'),
        ('Profile your code for performance.', '对代码进行性能分析。'),
        ('Monitor your code for issues.', '监控您的代码问题。'),
        ('Log your code appropriately.', '适当记录您的代码。'),
        ('Handle errors in your code.', '处理代码中的错误。'),
        ('Handle exceptions in your code.', '处理代码中的异常。'),
        ('Recover from errors in your code.', '从代码错误中恢复。'),
        ('Handle failures in your code.', '处理代码中的故障。'),
        ('Handle crashes in your code.', '处理代码中的崩溃。'),
        ('Handle timeouts in your code.', '处理代码中的超时。'),
        ('Manage resources in your code.', '管理代码中的资源。'),
        ('Prevent memory leaks in your code.', '防止代码中的内存泄漏。'),
        ('Clean up resources in your code.', '清理代码中的资源。'),
        ('Dispose of resources properly.', '正确释放资源。'),
        ('Manage resources effectively.', '有效管理资源。'),
        ('Allocate resources efficiently.', '高效分配资源。'),
        ('Deallocate resources properly.', '正确释放资源。'),
        ('Optimize resource usage.', '优化资源使用。'),
        ('Utilize resources efficiently.', '高效利用资源。'),
        ('Use resources efficiently.', '高效使用资源。'),
        ('Conserve resources in your code.', '在代码中节约资源。'),
        ('Preserve resources in your code.', '在代码中保护资源。'),
        ('Protect resources in your code.', '保护代码中的资源。'),
        ('Secure resources in your code.', '保护代码中的资源安全。'),
        ('Maintain resource integrity.', '维护资源完整性。'),
        ('Maintain resource consistency.', '维护资源一致性。'),
        ('Ensure resource reliability.', '确保资源可靠性。'),
        ('Ensure resource availability.', '确保资源可用性。'),
        ('Ensure resource accessibility.', '确保资源可访问性。'),
        ('Ensure resource usability.', '确保资源可用性。'),
        ('Ensure resource functionality.', '确保资源功能。'),
        ('Utilize resource features.', '利用资源特性。'),
        ('Leverage resource capabilities.', '利用资源能力。'),
        ('Maximize resource potential.', '最大化资源潜力。'),
        ('Extract resource value.', '提取资源价值。'),
        ('Realize resource benefits.', '实现资源收益。'),
        ('Leverage resource advantages.', '利用资源优势。'),
        ('Seize resource opportunities.', '抓住资源机会。'),
        ('Address resource challenges.', '应对资源挑战。'),
        ('Mitigate resource risks.', '降低资源风险。'),
        ('Counter resource threats.', '对抗资源威胁。'),
        ('Address resource vulnerabilities.', '应对资源脆弱性。'),
        ('Minimize resource exposure.', '最小化资源暴露。'),
        ('Assess resource impact.', '评估资源影响。'),
        ('Manage resource consequences.', '管理资源后果。'),
        ('Optimize resource outcomes.', '优化资源结果。'),
        ('Achieve resource results.', '实现资源结果。'),
        ('Maximize resource output.', '最大化资源输出。'),
        ('Increase resource yield.', '提高资源产出。'),
        ('Maximize resource return.', '最大化资源回报。'),
        ('Earn resource rewards.', '赚取资源回报。'),
        ('Realize resource gains.', '实现资源收益。'),
        ('Generate resource profit.', '产生资源利润。'),
        ('Increase resource income.', '增加资源收入。'),
        ('Maximize resource revenue.', '最大化资源收入。'),
        ('Boost resource earnings.', '提升资源收益。'),
        ('Collect resource proceeds.', '收集资源收益。'),
        ('Track resource receipts.', '跟踪资源收入。'),
        ('Monitor resource inflow.', '监控资源流入。'),
        ('Manage resource influx.', '管理资源涌入。'),
        ('Control resource injection.', '控制资源注入。'),
        ('Process resource input.', '处理资源输入。'),
        ('Ensure resource supply.', '确保资源供应。'),
        ('Provide resource provisions.', '提供资源供给。'),
        ('Complete resource provisioning.', '完成资源供应。'),
        ('Prepare resources adequately.', '充分准备资源。'),
        ('Ensure resource readiness.', '确保资源就绪。'),
        ('Confirm resource availability.', '确认资源可用性。'),
        ('Grant resource access.', '授予资源访问权限。'),
        ('Set resource permissions.', '设置资源权限。'),
        ('Authorize resource access.', '授权资源访问。'),
        ('Authenticate resource access.', '认证资源访问。'),
        ('Verify resource access.', '验证资源访问。'),
        ('Validate resource access.', '验证资源访问。'),
        ('Confirm resource access.', '确认资源访问。'),
        ('Approve resource access.', '批准资源访问。'),
        ('Endorse resource access.', '认可资源访问。'),
        ('Recommend resource access.', '推荐资源访问。'),
        ('Suggest resource access.', '建议资源访问。'),
        ('Advise on resource access.', '就资源访问提供建议。'),
        ('Guide resource access.', '指导资源访问。'),
        ('Direct resource access.', '指导资源访问。'),
        ('Instruct resource access.', '指示资源访问。'),
        ('Command resource access.', '命令资源访问。'),
        ('Order resource access.', '命令资源访问。'),
        ('Request resource access.', '请求资源访问。'),
        ('Inquire about resource access.', '查询资源访问。'),
        ('Question resource access.', '质疑资源访问。'),
        ('Query resource access.', '查询资源访问。'),
        ('Search for resources.', '搜索资源。'),
        ('Discover resources.', '发现资源。'),
        ('Explore resources.', '探索资源。'),
        ('Investigate resources.', '调查资源。'),
        ('Examine resources.', '检查资源。'),
        ('Inspect resources.', '检查资源。'),
        ('Review resources.', '审查资源。'),
        ('Audit resources.', '审计资源。'),
        ('Assess resources.', '评估资源。'),
        ('Evaluate resources.', '评价资源。'),
        ('Analyze resources.', '分析资源。'),
        ('Study resources.', '研究资源。'),
        ('Research resources.', '研究资源。'),
        ('Inquire about resources.', '查询资源。'),
        ('Question resources.', '质疑资源。'),
        ('Challenge resources.', '挑战资源。'),
        ('Test resources.', '测试资源。'),
        ('Validate resources.', '验证资源。'),
        ('Verify resources.', '验证资源。'),
        ('Confirm resources.', '确认资源。'),
        ('Certify resources.', '认证资源。'),
        ('Accredit resources.', '认可资源。'),
        ('Authorize resources.', '授权资源。'),
        ('Permit resource access.', '允许资源访问。'),
        ('Allow resource access.', '允许资源访问。'),
        ('Clear resource access.', '清除资源访问。'),
        ('Approve resources.', '批准资源。'),
        ('Endorse resources.', '认可资源。'),
        ('Support resources.', '支持资源。'),
        ('Assist with resources.', '协助资源。'),
        ('Help with resources.', '帮助资源。'),
        ('Aid resources.', '援助资源。'),
        ('Service resources.', '服务资源。'),
        ('Care for resources.', '关怀资源。'),
        ('Attend to resources.', '关注资源。'),
        ('Consider resources.', '考虑资源。'),
        ('Think about resources.', '思考资源。'),
        ('Reflect on resources.', '反思资源。'),
        ('Meditate on resources.', '冥想资源。'),
        ('Contemplate resources.', '沉思资源。'),
        ('Ponder resources.', '深思资源。'),
        ('Deliberate on resources.', '斟酌资源。'),
        ('Consider resources carefully.', '仔细考虑资源。'),
        ('Examine resources carefully.', '仔细检查资源。'),
        ('Inspect resources carefully.', '仔细检查资源。'),
        ('Review resources carefully.', '仔细审查资源。'),
        ('Analyze resources carefully.', '仔细分析资源。'),
        ('Study resources carefully.', '仔细研究资源。'),
        ('Research resources carefully.', '仔细研究资源。'),
        ('Last Updated', '最后更新'),
        ('This document describes the guidelines for submitting apps to the Connect IQ Store.', '本文档描述提交应用到 Connect IQ 商店的审核指南。'),
        ('These Guidelines apply to any development or creation using the Connect IQ SDK.', '这些指南适用于使用 Connect IQ SDK 的任何开发或创建。'),
        ('device apps, widgets, watch faces, custom data fields, and audio content provider apps', '设备应用、小组件、表盘、自定义数据字段和音频内容提供者应用'),
        ('for ease of reference, we use the term "app" to cover all of these categories', '为方便起见，我们使用"应用"一词来涵盖所有这些类别'),
        ('These Guidelines are not an exhaustive set of rules.', '这些指南并非详尽无遗的规则集。'),
        ('we do not waive any of our rights under applicable law', '我们不会放弃根据适用法律享有的任何权利'),
        ('We may reject or remove a potentially harmful app from the Connect IQ store', '我们可能会从 Connect IQ 商店拒绝或移除潜在有害的应用'),
        ('even if there is no specific violation of the Guidelines', '即使没有明确违反指南'),
        ('You are responsible for your app.', '您对您的应用负责。'),
        ('We may reject or remove an app for any content or subject matter we believe is dangerous, offensive, inappropriate or unlawful.', '如果我们认为任何内容或主题是危险的、冒犯性的、不适当的或违法的，我们可能会拒绝或移除该应用。'),
        ('certain types of apps, such as aviation apps, medical apps, or apps that support user-generated content, may be allowed only if you comply with additional requirements', '某些类型的应用，如航空应用、医疗应用或支持用户生成内容的应用，只有在遵守额外要求的情况下才允许'),
        ('If your app doesn\'t function, diminishes battery life or other features of the Garmin device, or crashes frequently, it may be rejected or removed.', '如果您的应用无法运行、减少 Garmin 设备的电池寿命或其他功能，或频繁崩溃，可能会被拒绝或移除。'),
        ('The user experience begins with how you promote, describe, and monetize your app.', '用户体验从您如何推广、描述和变现您的应用开始。'),
        ('You must do so in a manner that is honest and fair to users and other apps', '您必须以诚实和公平的方式对待用户和其他应用'),
        ('Do not use copyrighted content or other intellectual property of others without their permission.', '未经许可不得使用受版权保护的内容或其他人的知识产权。'),
        ('Your app cannot use data in a way that violates the Connect IQ Developer Agreement or privacy laws.', '您的应用不得以违反 Connect IQ 开发者协议或隐私法律的方式使用数据。'),
        ('We expect our developers to comply, and we reserve the right to take steps to protect our users if these Guidelines are not followed.', '我们期望开发者遵守指南，并保留采取措施保护用户的权利，如果这些指南未被遵守。'),
        ('Potential issues with content and subject matter that ask you to avoid.', '要求您避免的内容和主题潜在问题。'),
        ('Your app should not include content that is unlawful, harmful, obscene, inappropriate, or offensive.', '您的应用不应包含违法、有害、淫秽、不适当或冒犯性的内容。'),
        ('We prohibit apps from including, linking to, or encouraging the creation of the following types of content:', '我们禁止应用包含、链接到或鼓励创建以下内容：'),
        ('Sexual or obscene content', '性或淫秽内容'),
        ('Including pornography, any content or services intended to be sexually gratifying', '包括色情内容，任何旨在满足性欲的内容或服务'),
        ('any content relating to bestiality or non-consensual sex', '任何涉及兽交或未经同意的性行为的内容'),
        ('explicit descriptions or displays of sexual organs or activities', '性器官或活动的明确描述或展示'),
        ('Bullying, harassment, and abuse', '欺凌、骚扰和虐待'),
        ('Profanity or defamatory, fraudulent, infringing, or other unlawful content', '亵渎、诽谤、欺诈、侵权或其他违法内容'),
        ('Spam or advertising-focused content that serves primarily to drive affiliate traffic to a website', '垃圾邮件或广告导向内容，主要目的是将联盟流量驱动到网站'),
        ('Gambling', '赌博'),
        ('Any other inappropriate or offensive Content', '任何其他不适当或冒犯性内容'),
        ('We reserve the right to reject or remove any app that, in our opinion, creates any risk of liability to Garmin', '我们保留拒绝或移除任何在我们看来给 Garmin 带来责任风险的应用的权利'),
        ('threatens any type of harm to our users or third parties', '对我们的用户或第三方造成任何类型的伤害'),
        ('could harm our reputation', '可能损害我们的声誉'),
        ('This includes, but is not limited to, any content that directly or indirectly violates other of our terms or guidelines.', '这包括但不限于任何直接或间接违反我们其他条款或指南的内容。'),
        ('Your app must not threaten the physical safety or well-being of users or anyone else.', '您的应用不得威胁用户或其他人的物理安全或健康。'),
        ('We reserve the right to reject any app that we believe is unsafe or could, directly or indirectly, cause anyone harm.', '我们保留拒绝任何我们认为不安全或可能直接或间接对任何人造成伤害的应用的权利。'),
        ('This includes apps that may create a false sense of security', '这包括可能制造虚假安全感的应用'),
        ('such as "safety awareness" apps', '例如"安全意识"应用'),
        ('Your app should not encourage or challenge users to act or use devices in a manner that risks physical harm to themselves or others.', '您的应用不应鼓励或挑战用户以可能对自己或他人造成物理伤害的方式行动或使用设备。'),
        ('For example, apps should not challenge users to perform exercises or activities in a manner likely to result in injury or to drink excessive amounts of alcohol.', '例如，应用不应挑战用户以可能导致受伤或饮用过量酒精的方式执行锻炼或活动。'),
        ('We prohibit apps that are designed to be used during dangerous activities such as scuba diving, free diving, skydiving, base-jumping, and extreme flight sports', '我们禁止设计用于潜水、自由潜水、跳伞、BASE 跳伞和极限飞行运动等危险活动的应用'),
        ('even if your app is designed to work with one of Garmin\'s products that has been designed for those activities', '即使您的应用设计用于与 Garmin 的产品一起使用，这些产品也是为这些活动设计的'),
        ('For example, you may create apps that add functionality to a Garmin Descent series dive watch', '例如，您可以创建为 Garmin Descent 系列潜水表添加功能的应用'),
        ('your app should not be intended only for use during a user\'s dive', '您的应用不应仅用于用户潜水期间'),
        ('We do not allow apps to facilitate or encourage gratuitous violence, human rights violations, domestic violence, child or animal abuse, or similar actions that harm the user or others.', '我们不允许应用促进或鼓励无端的暴力行为、侵犯人权、家庭暴力、儿童或动物虐待或其他伤害用户或他人的类似行为。'),
        ('Apps should not promote the use of illegal drugs, tobacco or vape products, excessive amounts of alcohol, unapproved substances, and illegal or dangerous products.', '应用不得推广非法药物、烟草或电子烟产品、过量酒精、未经批准的物质和非法或危险产品。'),
        ('We will allow appropriate aviation-themed apps', '我们将允许适当的航空主题应用'),
        ('in addition to any other legally required disclaimers, aviation apps (except watch faces) must include the following disclaimer', '除了任何其他法律要求的免责声明外，航空应用（不包括表盘）必须包含以下免责声明'),
        ('WARNING: The app is intended only as an in-flight aid and should not be used as a primary information source. If the app contains a barometric altimeter, it will not function in a pressurized aircraft and should not be used in a pressurized aircraft.', '警告：该应用仅作为飞行辅助工具，不应作为主要信息来源。如果应用包含气压高度计，它将无法在加压飞机中运行，不应在加压飞机中使用。'),
        ('You are solely responsible for ensuring that your app complies with laws and regulations and includes any legally-required disclaimer.', '您完全负责确保您的应用遵守法律法规并包含任何法律要求的免责声明。'),
        ('We encourage you to seek independent legal advice where appropriate, especially if your app relates to regulated activities, including the practice of medicine, law, or financial services.', '我们鼓励您在适当情况下寻求独立法律建议，特别是如果您的应用涉及监管活动，包括医学、法律或金融服务。'),
        ('If your app is intended for use in the diagnosis, cure, mitigation, treatment or prevention of disease or other conditions', '如果您的应用旨在用于诊断、治愈、缓解、治疗或预防疾病或其他状况'),
        ('you must be prepared to submit documentation from any relevant regulatory agencies proving the app is cleared for use in your target markets.', '您必须准备提交任何相关监管机构的文件，证明该应用已获准在目标市场使用。'),
        ('Otherwise, you must update the app\'s description, features and functionality to ensure it does not indicate any use for the purposes of diagnosis, cure, prevention, mitigation or treatment of disease or other conditions and is intended for informational purposes only.', '否则，您必须更新应用的描述、功能和特性，确保其不表明任何用于诊断、治愈、预防、缓解或治疗疾病或其他状况的用途，并且仅 intended 用于信息目的。'),
        ('Even if your app has been cleared by a regulatory agency, we reserve the right to accept or reject the app based on these Guidelines.', '即使您的应用已获得监管机构批准，我们仍保留根据这些指南接受或拒绝该应用的权利。'),
        ('We do not allow any apps that introduce or exploit security vulnerabilities.', '我们不允许任何引入或利用安全漏洞的应用。'),
        ('This includes, but is not limited to, apps that contain or enable any malicious software, including viruses, spyware, disabling code, or other software designed to damage a device or server or violate the privacy of our users.', '这包括但不限于包含或启用任何恶意软件的应用，包括病毒、间谍软件、禁用代码或其他旨在损坏设备或服务器或侵犯我们用户隐私的软件。'),
        ('You are responsible for screening your apps for malicious software prior to submitting.', '您负责在提交前筛查应用中的恶意软件。'),
        ('We prohibit apps from using Garmin devices to mine for cryptocurrency.', '我们禁止应用使用 Garmin 设备进行加密货币挖矿。'),
        ('We prohibit apps that are designed to be used by children under the age of 13.', '我们禁止设计供13岁以下儿童使用的应用。'),
        ('This prohibition does not apply to any general audience apps, unless you are aware that the app is used by children under the age of 13.', '此禁令不适用于任何面向大众的应用，除非您知道该应用被13岁以下儿童使用。'),
        ('If you offer features that allow the publication of user-generated content to the general public or other users in your app', '如果您提供允许在应用中向公众或其他用户发布用户生成内容的功能'),
        ('you are responsible for moderating the content, as necessary, to prevent any unlawful, infringing or inappropriate content.', '您负责酌情审核内容，以防止任何违法、侵权或不适当的内容。'),
        ('"User-generated content" includes text, images, sound, or other data submitted or uploaded by users or third parties.', '"用户生成内容"包括用户或第三方提交或上传的文本、图像、声音或其他数据。'),
        ('Have an agreement with end users that prohibits unlawful, harmful, obscene, inappropriate, or offensive content', '与最终用户达成协议，禁止违法、有害、淫秽、不适当或冒犯性内容'),
        ('see 1(b) – Prohibited Content, above', '参见1(b) - 禁止内容，上文'),
        ('Maintain a method for users to report any inappropriate or prohibited content', '维护用户报告任何不适当或禁止内容的方法'),
        ('Publish a DMCA-compliant policy to remove content that infringes the intellectual property rights of third parties.', '发布符合 DMCA 的政策，移除侵犯第三方知识产权的内容。'),
        ('If you fail to moderate your app\'s user-generated content, we reserve the right to take action to suspend or remove your app', '如果您未能审核应用中的用户生成内容，我们保留采取行动暂停或移除您的应用的权利'),
        ('just as if your own content violated these Guidelines.', '就像您自己的内容违反了这些指南一样。'),
        ('Our users expect a high-quality experience when using Garmin products.', '我们的用户在使用 Garmin 产品时期望高质量的体验。'),
        ('These Guidelines are intended to help ensure that apps perform to our users\' expectations.', '这些指南旨在帮助确保应用达到用户的期望。'),
        ('Your app should do no harm.', '您的应用不得有害。'),
        ('Apps must not interfere with the use or enjoyment of other apps or features, such as the activity experience, battery life, device performance, etc.', '应用不得干扰其他应用或功能的使用或享受，如活动体验、电池寿命、设备性能等。'),
        ('We do not allow apps that damage, disrupt or access in an unauthorized manner the user\'s Garmin device, other devices or computers, networks, servers, application programming interfaces (APIs), or services.', '我们不允许以未经授权的方式损坏、破坏或访问用户 Garmin 设备、其他设备或计算机、网络、服务器、应用程序编程接口（API）或服务的应用。'),
        ('The app should not require changes to system settings that will adversely affect the performance of other features on the device.', '应用不应要求更改系统设置，这将对设备上其他功能的性能产生不利影响。'),
        ('Apps should not cause Garmin\'s products to no longer meet their expected battery life.', '应用不应导致 Garmin 产品不再满足预期的电池寿命。'),
        ('cause other apps to run more slowly', '导致其他应用运行更慢'),
        ('attempt to access data in an unauthorized manner', '尝试未经授权访问数据'),
        ('otherwise disrupt the advertised or desired user experience', '否则破坏宣传的或期望的用户体验'),
        ('We do not allow apps to override information previously synced to their Connect account', '我们不允许应用覆盖先前同步到其 Connect 账户的信息'),
        ('where such data fields typically come from the Garmin device itself', '其中此类数据字段通常来自 Garmin 设备本身'),
        ('We want to maintain the integrity and reliability of data values collected or generated by Garmin\'s devices and software.', '我们希望维护 Garmin 设备和软件收集或生成的数据值的完整性和可靠性。'),
        ('Apps should not require or encourage the use of a Garmin device in a manner likely to harm the device.', '应用不应要求或鼓励以可能损害设备的方式使用 Garmin 设备。'),
        ('the app should not be designed for use during activities that will expose the device to harmful levels of heat or water pressure', '应用不应设计用于会将设备暴露在有害热量或水压下的活动'),
        ('By the time you submit, your app should be fully completed, tested, and ready for use.', '提交时，您的应用应已完成、测试并准备就绪。'),
        ('You should ensure that your app provides a stable, engaging, and responsive user experience.', '您应确保您的应用提供稳定、吸引人且响应迅速的用户体验。'),
        ('The app should not contain any broken links or functionality.', '应用不应包含任何损坏的链接或功能。'),
        ('We are not responsible for providing customer support for your app or fielding complaints.', '我们不负责为您的应用提供客户支持或处理投诉。'),
        ('You should clearly explain to users your support policy and availability.', '您应向用户清楚解释您的支持政策和可用性。'),
        ('It is your responsibility to follow through on whatever support commitments you make.', '您有责任兑现您所做的任何支持承诺。'),
        ('These Guidelines describe potential issues with content and subject matter that ask you to avoid.', '这些指南描述了要求您避免的内容和主题潜在问题。'),
        ('You may not infringe any copyright, trademark, patent, trade secret, or any other form of intellectual property ("IP").', '您不得侵犯任何版权、商标、专利、商业秘密或任何其他形式的知识产权（"IP"）。'),
        ('You must own or have a license to use all IP included in or used by your app.', '您必须拥有或获得许可才能使用应用中包含或使用的所有知识产权。'),
        ('This includes your app\'s software and content (other than user generated content, discussed below), your developer account name, as well as the logos, images, and content that you use to promote your app in the Connect IQ store.', '这包括您的应用的软件和内容（除下文讨论的用户生成内容外）、您的开发者账户名称以及您在 Connect IQ 商店中推广应用时使用的标志、图像和内容。'),
        ('It is your responsibility to ensure IP compliance and non-infringement.', '您有责任确保知识产权合规和不侵权。'),
        ('If you are unsure if your use of IP is infringing, check with a lawyer.', '如果您不确定您的知识产权使用是否侵权，请咨询律师。'),
        ('It is not for us to decide whether your use of a third party\'s IP may be infringing, properly used under a license, or fair use.', '决定您对第三方知识产权的使用是否侵权、在许可下正确使用或合理使用，不是我们的职责。'),
        ('It is your responsibility to get permission as necessary from the IP owner before using their materials.', '您有责任在使用其材料前从知识产权所有者处获得必要的许可。'),
        ('Get permission in writing, keep a record of the permission, and make sure you\'re complying with any terms and conditions.', '以书面形式获得许可，记录许可，并确保遵守任何条款和条件。'),
        ('Your app may be the perfect complement for someone else\'s product or brand.', '您的应用可能是他人产品或品牌的完美补充。'),
        ('That doesn\'t mean you have a right to use their intellectual property.', '这并不意味着您有权使用他们的知识产权。'),
        ('Be careful before making any mention of a brand or using any logo or name that is not yours.', '在提及任何品牌或使用任何非您自己的标志或名称之前请谨慎。'),
        ('If you have questions about someone\'s IP, you should ask the IP owner, not us (unless it is Garmin\'s IP).', '如果您对某人的知识产权有疑问，您应该询问知识产权所有者，而不是我们（除非是 Garmin 的知识产权）。'),
        ('Garmin maintains a DMCA policy for IP owners to notify Garmin of alleged infringement.', 'Garmin 为知识产权所有者维护 DMCA 政策，以通知 Garmin 所谓的侵权行为。'),
        ('In some situations, we may need to remove or suspend your app in accordance with our policy.', '在某些情况下，我们可能需要根据我们的政策移除或暂停您的应用。'),
        ('You can find the policy and additional details in our Terms of Use.', '您可以在我们的使用条款中找到政策和更多详情。'),
        ("Garmin's DMCA Policy is not a substitute for maintaining your own policy for moderating user-generated content.", "Garmin 的 DMCA 政策不能替代您自己审核用户生成内容的政策。"),
        ('in some cases, we may need take action against your app as the result of infringing user-generated content.', '在某些情况下，我们可能需要对您的应用采取行动，作为侵犯用户生成内容的结果。'),
        ('If your app collects and processes any user data, including any personal data', '如果您的应用收集和处理任何用户数据，包括任何个人数据'),
        ('you must comply with privacy laws and any other applicable laws and regulations', '您必须遵守隐私法律和任何其他适用的法律和法规'),
        ('as well as all privacy requirements stated in the Connect IQ Developer Agreement.', '以及 Connect IQ 开发者协议中规定的所有隐私要求。'),
        ('Think carefully before collecting and using personal data.', '在收集和使用个人数据之前仔细考虑。'),
        ('It is a best practice (and often a required practice) that you take all steps to minimize the collection, processing, and retention of personal data as much as possible.', '这是最佳实践（通常也是必需的），您应采取一切措施尽可能减少个人数据的收集、处理和保留。'),
        ('Publish and make available your own privacy policy or other notice concerning your processing of personal data and how users may contact you to exercise any of their privacy rights.', '发布并提供您自己的隐私政策或其他通知，说明您如何处理个人数据以及用户如何联系您行使任何隐私权利。'),
        ('You cannot rely on Garmin\'s privacy policies, which only describe Garmin\'s privacy practices.', '您不能依赖 Garmin 的隐私政策，这些政策仅描述 Garmin 的隐私实践。'),
        ('Where appropriate, seek permission from users prior to collecting location data or data that may be considered sensitive.', '在适当情况下，在收集位置数据或可能被视为敏感的数据之前寻求用户许可。'),
        ('After obtaining permission, use the data only in accordance with that permission.', '获得许可后，仅按照该许可使用数据。'),
        ('You are responsible for complying with any legal obligations to obtain consent, even if doing so would require you to take steps outside of the Connect IQ framework for your particular use case.', '您有责任遵守任何获得同意的法律义务，即使这样做需要您在 Connect IQ 框架之外采取措施以适应您的特定用例。'),
        ('We want users to download, install, and use your app.', '我们希望用户下载、安装和使用您的应用。'),
        ('Promoting your app starts with a strong description in the Connect IQ store but can also include advertising the app in your own channels.', '推广您的应用始于 Connect IQ 商店中的强大描述，但也可以包括在自己的渠道中推广应用。'),
        ('We expect you to advertise in a fair, lawful and transparent manner.', '我们期望您以公平、合法和透明的方式做广告。'),
        ('You must not make any inaccurate or misleading statements.', '您不得做出任何不准确或误导性的陈述。'),
        ('The information you provide about your app when submitting it to the app store should include a complete description of all features and any minimum requirements, limitations, or dependencies.', '您向应用商店提交应用时提供的信息应包括所有功能的完整描述以及任何最低要求、限制或依赖关系。'),
        ('This also applies to any other advertising you for your app, whether or not on a Garmin digital property, and any content or metadata associated with your app.', '这也适用于您为您的应用做的任何其他广告，无论是否在 Garmin 数字财产上，以及与您的应用相关的任何内容或元数据。'),
        ('Use your or your company\'s real name or an alias that does not impersonate another person or company.', '使用您或您公司的真实名称或不冒充其他人或公司的别名。'),
        ('Keep your contact information up-to-date.', '保持您的联系信息最新。'),
        ('Avoid claiming any partnership or affiliation with Garmin, unless we have given you express written permission.', '避免声称与 Garmin 有任何合作伙伴关系或关联，除非我们已给予您明确的书面许可。'),
        ('Do not claim your app is compatible with any third-party system or protocol, if you have not obtained any required certification necessary to support such compatibility claim.', '如果您未获得支持此类兼容性声明所需的任何必要认证，请勿声称您的应用与任何第三方系统或协议兼容。'),
        ('Identify whether your app requires any specific Garmin or third-party hardware or software to operate.', '明确您的应用是否需要任何特定的 Garmin 或第三方硬件或软件才能运行。'),
        ('For example, if the app\'s core features do not work without ANT+, you must disclose that.', '例如，如果应用的核心功能在没有 ANT+ 的情况下无法工作，您必须披露这一点。'),
        ('If a specific feature has a dependency, you must disclose that dependency when advertising that the specific feature.', '如果特定功能有依赖关系，您在宣传该特定功能时必须披露该依赖关系。'),
        ('You must accurately disclose which Garmin devices support your app.', '您必须准确披露哪些 Garmin 设备支持您的应用。'),
        ('Because Garmin regularly releases new products, we encourage you to keep this list up-to-date.', '因为 Garmin 定期发布新产品，我们鼓励您保持此列表最新。'),
        ('At minimum, you must avoid falsely claiming that your app works with a certain Garmin device.', '至少，您必须避免虚假声称您的应用与某个 Garmin 设备兼容。'),
        ('If your app supports ANT or ANT+ profiles, you must list all profiles your app supports.', '如果您的应用支持 ANT 或 ANT+ 配置文件，您必须列出您的应用支持的所有配置文件。'),
        ('where applicable, your app must pass ANT+ certification.', '在适用的情况下，您的应用必须通过 ANT+ 认证。'),
        ('You must not perform or encourage any action that creates deceptive reviews or manipulates your app\'s rating.', '您不得执行或鼓励任何创建欺骗性评论或操纵您的应用评分的操作。'),
        ('Disguise yourself as a user to publish positive reviews of your app or negative reviews of another developer\'s app.', '伪装成用户发布您应用的正面评论或其他开发者应用的负面评论。'),
        ('Pay for positive reviews, including by offering users discounts on your products in exchange for a positive review or rating.', '付费购买正面评论，包括通过向用户提供产品折扣来换取正面评论或评分。'),
        ('even if you disclose your material connection to the reviewer.', '即使您披露了与评论者的实质性关联。'),
        ('Submit a rating for your own app.', '为您自己的应用提交评分。'),
        ('You must identify whether or not your app requires payment.', '您必须明确您的应用是否需要付费。'),
        ('An app requires payment if the user must pay to access or use any primary feature of the app', '如果用户必须付费才能访问或使用应用的任何主要功能，则应用需要付费'),
        ('those features that are advertised in the app\'s description, excluding any features that are clearly labeled optional', '应用在描述中宣传的功能，不包括任何明确标记为可选的特性'),
        ('In contrast, an app is not considered to require payment, if the only features that require payment or subscription are optional.', '相反，如果唯一需要付费或订阅的功能是可选的，则应用不被视为需要付费。'),
        ('You must be honest when describing any payment requirements, whether optional or not.', '在描述任何付款要求时必须诚实，无论是可选的还是必选的。'),
        ('Disclose from the outset if your app is only free for a limited time or for a limited number of uses.', '从一开始就披露您的应用是否仅在有限时间内或有限次数内免费。'),
        ('Inform users of your refund policy or lack thereof.', '告知用户您的退款政策或缺乏退款政策。'),
        ('Not "bait-and-switch" users by implying that a feature is available for free, when it is not.', '不要通过暗示功能可免费使用来"诱饵和替换"用户，而实际上并非如此。'),
        ('Obtain express consent for any auto-renewal of payments, regardless of whether required to do so by law.', '获得任何付款自动续期的明确同意，无论法律是否要求这样做。'),
        ('Garmin intends to enforce these Guidelines by rejecting or removing apps, if necessary to stop or prevent violations.', 'Garmin 打算通过拒绝或移除应用来执行这些指南，如有必要以阻止或防止违规行为。'),
        ('Garmin, in its discretion, may choose to contact developers and request changes to apps, but Garmin is not required to provide notice prior to suspending or removing an app.', 'Garmin 可自行选择联系开发者并请求更改应用，但 Garmin 不需要在暂停或移除应用前提供通知。'),
        ('When you submit an app for approval, we expect the app to be ready to meet all of our Guidelines.', '当您提交应用以供审批时，我们期望应用已准备好满足我们所有的指南。'),
        ('We endeavor to review the app and the related documentation as thoroughly and promptly as possible.', '我们努力尽可能彻底和及时地审查应用及相关文档。'),
        ('Please keep in mind that even if an app is approved, we may later discover issues after the review process.', '请记住，即使应用已获批准，我们也可能在审查过程后发现问题。'),
        ('If we find an issue with an app, whether discovered by us or brought to our attention by a user', '如果我们发现应用的问题，无论是由我们发现还是由用户提请我们注意'),
        ('we endeavor to provide an opportunity for the developer to resubmit with feedback.', '我们努力为开发者提供重新提交并获得反馈的机会。'),
        ('If the issue presents significant risks to Garmin or our users, we may immediately suspend the ability to download or use the app.', '如果问题对 Garmin 或我们的用户构成重大风险，我们可能立即暂停下载或使用应用的能力。'),
        ('We are under no obligation to provide you with any notice or process before taking action.', '我们在采取行动前没有义务向您提供任何通知或流程。'),
        ('Garmin reserves all rights to take any actions necessary to protect its users, products, brand, reputation, etc.', 'Garmin 保留采取任何必要措施保护其用户、产品、品牌、声誉等的权利。'),
        ('This means that even if we remove an app, we can still exercise all available legal or equitable remedies.', '这意味着即使我们移除了应用，我们仍可以行使所有可用的法律或衡平法救济。'),
        ('Despite our right to enforce these Guidelines, we hope to avoid the need to take any action.', '尽管我们有权执行这些指南，我们希望避免采取任何行动的必要性。'),
        ('We want your app to be a success. If you have questions about Connect IQ or these Guidelines', '我们希望您的应用取得成功。如果您对 Connect IQ 或这些指南有疑问'),
        ('please feel free to ask a question in our developer forums.', '请随时在我们的开发者论坛中提问。'),
        ('App Review Guidelines', '应用审核指南'),
        ('Connect IQ App Developer Guidelines', 'Connect IQ 应用开发者指南'),
        ('these "Guidelines"', '这些"指南"'),
        ('Summary', '摘要'),
        ('Enforcement', '执行'),
        ('Approval Process', '审批流程'),
        ('Removal Process', '移除流程'),
        ('Reservation of Rights', '保留权利'),
        ('Contact Us', '联系我们'),
        ('Prohibited Content', '禁止内容'),
        ('Physical Safety', '物理安全'),
        ('Medical Apps', '医疗应用'),
        ('No Malware or Harmful Apps', '禁止恶意软件或有害应用'),
        ('No Mining for Cryptocurrency', '禁止加密货币挖矿'),
        ('No Apps for Children under 13', '禁止13岁以下儿童使用'),
        ('User-Generated Content', '用户生成内容'),
        ('Describe Your App Accurately and Completely', '准确完整地描述您的应用'),
        ('Compatibility with Garmin Devices and ANT or ANT+ Communications Protocols', '与 Garmin 设备和 ANT 或 ANT+ 通信协议的兼容性'),
        ('No Review or Rating Manipulation', '禁止评论或评分操纵'),
        ('Monetization of Your App', '您的应用变现'),
        ('No Infringement', '禁止侵权'),
        ('Garmin\'s DMCA Policy', 'Garmin 的 DMCA 政策'),
        ('Privacy and Data Use', '隐私和数据使用'),
        ('Promoting and Monetizing Your App', '推广和变现您的应用'),
        ('Do Not Harm the Garmin Experience', '不得损害 Garmin 体验'),
        ('Support', '支持'),
        ('Respect the Rights of Others, including IP and Privacy Rights', '尊重他人的权利，包括知识产权和隐私权'),
        ('Appropriate Content and Subject Matter', '适当的内容和主题'),
        ('Performance Requirements', '性能要求'),
        ('Glossary', '词汇表'),
        ('API', 'API'),
        ('app', '应用'),
        ('Connect IQ Store', 'Connect IQ 商店'),
        ('Connect IQ Developer Agreement', 'Connect IQ 开发者协议'),
        ('DMCA', 'DMCA'),
        ('IP', '知识产权'),
        ('SDK', 'SDK'),
        ('Terms of Use', '使用条款'),
        ('Watch Faces', '表盘'),
        ('widgets', '小组件'),
        ('custom data fields', '自定义数据字段'),
        ('audio content provider apps', '音频内容提供者应用'),
        ('device apps', '设备应用'),
    ],
}
